# build stage
FROM node:16-alpine as build-stage
ENV REACT_APP_SERVER_PORT=4000
WORKDIR /client
COPY . .
RUN npm install
RUN REACT_APP_SERVER_PORT=$REACT_APP_SERVER_PORT npm run build

# production stage
FROM nginx:1.17-alpine as production-stage
COPY --from=build-stage /client/build /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
