# build stage
FROM node:22-alpine as build-stage

ARG REACT_APP_SERVER_PORT

ARG REACT_APP_SERVER_HOST

WORKDIR /client

COPY . .

RUN npm install

RUN REACT_APP_SERVER_PORT=$REACT_APP_SERVER_PORT REACT_APP_SERVER_HOST=$REACT_APP_SERVER_HOST npm run build

# production stage
FROM nginx:1.17-alpine as production-stage
COPY --from=build-stage /client/build /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
