FROM golang:1.20

WORKDIR /server  

COPY go.mod go.sum ./

RUN go env -w GO111MODULE=auto

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o=./bin/api ./cmd/api

EXPOSE 4000

CMD ["./bin/api"]