FROM golang:1.20

ENV SERVER_PORT=4000

WORKDIR /server  

COPY go.mod go.sum ./

RUN go env -w GO111MODULE=auto

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o=./bin/api ./cmd/api

EXPOSE $SERVER_PORT

CMD ["./bin/api"]