# Use an official Python runtime as the base image
FROM python:3.9-slim

ENV AI_PORT=4001

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file and install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code into the container
COPY . .

# Expose the port on which the application will run
EXPOSE ${AI_PORT}

# Run the FastAPI application
CMD ["python3", "main.py"]